field: 1f9ee18e-e211-4106-90a4-9b7f02372d28
fieldLayouts:
  0c9f1da7-62b4-444a-8576-965d7dfcf766:
    tabs:
      -
        elements:
          -
            fieldUid: 65e36fb8-4421-4856-bd00-9e2203e673dc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0c6c684b-a6ca-4c21-852b-c7aa7d5b5dee
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ed339bfc-c0e4-43b3-ba8f-be1b7175751f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0c6c684b-a6ca-4c21-852b-c7aa7d5b5dee:
    contentColumnType: text
    fieldGroup: null
    handle: authorTitle
    instructions: ''
    name: 'Author title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  65e36fb8-4421-4856-bd00-9e2203e673dc:
    contentColumnType: text
    fieldGroup: null
    handle: authorName
    instructions: ''
    name: 'Author name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ed339bfc-c0e4-43b3-ba8f-be1b7175751f:
    contentColumnType: text
    fieldGroup: null
    handle: authorCompany
    instructions: ''
    name: 'Author company'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: authorMatrix
name: 'Author Matrix'
sortOrder: 1
