field: ff7424d6-2f4c-44cf-b9cd-a9c40c99c203
fieldLayouts:
  b57fab07-55bd-4a6a-8ee7-99896f7ec20c:
    tabs:
      -
        elements:
          -
            fieldUid: e0acc86d-fd6a-49ce-a120-e6ee7f62e3c8
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0911b495-56da-47df-81d7-3b0e5b1602ab
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0911b495-56da-47df-81d7-3b0e5b1602ab:
    contentColumnType: string(255)
    fieldGroup: null
    handle: buttonURL
    instructions: ''
    name: 'Button URL'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  e0acc86d-fd6a-49ce-a120-e6ee7f62e3c8:
    contentColumnType: text
    fieldGroup: null
    handle: buttonCTA
    instructions: ''
    name: 'Button CTA'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: button
name: Button
sortOrder: 1
