field: 01f0e8b1-0ad8-42dd-90e0-3c5753af7b51
fieldLayouts:
  8569b7d6-7aa7-4eae-885f-5621ffc36e3f:
    tabs:
      -
        elements:
          -
            fieldUid: acf20996-8724-4ba2-9896-1457b5ced4fe
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0a0b532a-015f-4eea-b519-d0cdc8c0093e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fdccf06c-5f0e-4932-bd89-1c06d94fb66b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0a0b532a-015f-4eea-b519-d0cdc8c0093e:
    contentColumnType: text
    fieldGroup: null
    handle: blockTitle
    instructions: ''
    name: 'Block title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  acf20996-8724-4ba2-9896-1457b5ced4fe:
    contentColumnType: string
    fieldGroup: null
    handle: blockIcon
    instructions: ''
    name: 'Block icon'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:8f179eeb-233d-42c2-82af-ffff018d0f53' # Images
      defaultUploadLocationSubpath: /approach
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:8f179eeb-233d-42c2-82af-ffff018d0f53' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:8f179eeb-233d-42c2-82af-ffff018d0f53' # Images
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  fdccf06c-5f0e-4932-bd89-1c06d94fb66b:
    contentColumnType: text
    fieldGroup: null
    handle: blockCopy
    instructions: ''
    name: 'Block copy'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: contentblock
name: contentBlock
sortOrder: 1
