fieldLayouts:
  13121129-d041-4338-bc32-9cead7766425:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 0ad26c4a-0a51-446f-8a32-8636c09ab27c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e9439491-9dea-4ad1-9a6d-03556df453c1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: df3aea1a-ed46-4bbd-945e-7088526543b3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 79db30b0-00dd-44b4-9574-71c25930c2bf
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 77a3cc7a-b365-4e81-9c2c-4df42b68d05f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 412aca6a-33da-4a96-84a9-ef86ce41d1d7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 73675380-191f-4043-b50b-a8b3b8be9c1b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 0160ea70-0eea-4ca4-ac1c-0d2cd36f2d03
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 01f0e8b1-0ad8-42dd-90e0-3c5753af7b51
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: a718e0e5-ced8-4bfc-9558-814cc0ef618c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4fe92e6f-ea33-473d-aeba-b280071320bc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c1ca6812-6064-47b1-8ef6-505183ba3475
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 74c55c95-24ef-4e03-b375-7509209f110a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a781bbbf-3b4d-4337-8b6c-b8b969740954
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: approach
hasTitleField: false
name: Approach
section: 45c1a7a2-254b-45cb-94a3-5405bf417a5e
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
