allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  aaa0c42e-156d-41ba-92a5-328e2f00cf6b:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8283692c-1418-4dba-9e54-4cbf25ca1eca
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e9439491-9dea-4ad1-9a6d-03556df453c1 # subtitle
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f5f304a-f85e-4dcf-9bfc-3a80e8912eeb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: df3aea1a-ed46-4bbd-945e-7088526543b3 # Feature image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ad606dc-5b36-4505-94c9-845de8df8572
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b631c5e9-e0aa-4992-ad62-57b199265e11
        userCondition: null
    thumbFieldKey: null
handle: contact
hasTitleField: true
icon: null
name: Contact
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
