fieldLayouts:
  cfdb30d3-5cb1-4b71-bdd8-ade59a6c62b2:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 0ad26c4a-0a51-446f-8a32-8636c09ab27c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e9439491-9dea-4ad1-9a6d-03556df453c1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: df3aea1a-ed46-4bbd-945e-7088526543b3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: leadspace
hasTitleField: false
name: Leadspace
section: 111bd820-8405-491f-905c-a2a42272a340
sortOrder: 2
titleFormat: '{pageTitle}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
