fieldLayouts:
  9bbeecee-94d6-4161-af0d-23da7e00f105:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4d03acdc-3297-460f-ae07-bde6e54add00
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f17c26fd-7e6b-4e81-9802-443737d8fa84
        userCondition: null
handle: newContact
hasTitleField: false
name: 'New Contact'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
