fieldLayouts:
  18b2dd56-07bb-4a9d-8157-d442b73c59de:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ef441e6d-d2b5-4112-8425-da763a68bfa4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c129c9af-0886-4586-9c57-7ace0539a0fb
        userCondition: null
handle: offer
hasTitleField: false
name: 'What We Offer'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
