allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  5d89cce1-2607-4fd3-b8e8-643b574c7289:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 282b14f1-28fc-44d1-9ce5-43aaa41aeb7b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 2561f0d0-6ec8-4a80-b535-5163d869847d # Team member title
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9671b37-a78c-497e-b3ff-ad70753ca334
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4f87d506-cb1f-4659-aac4-cc64aa7e23d7 # Team member headshot
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5423a19a-94e2-40c7-82df-e3613dcefa9f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ca9327e2-e1b3-464b-a57d-d6a939189245 # Body copy
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28c18380-50f6-4fe4-bc51-fea9c9b20802
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d90cf364-559e-42af-b83d-5c61fd1a4c5e
        userCondition: null
    thumbFieldKey: null
handle: team
hasTitleField: true
icon: null
name: Team
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
