fieldLayouts:
  0e00709e-05c2-46fe-b72c-1abf18d830ec:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 265d4d58-2603-4a8f-ac74-f3ea72fea3f7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b1b257a1-5df3-41fb-8866-c53a2c26173f
        userCondition: null
handle: wizard
hasTitleField: false
name: Wizard
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
