allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  78a73b2f-42b9-425e-b981-ac74039f18fb:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3e9d304d-f0bf-4ef8-b91a-13fb163706f0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fcd38684-250c-4fdb-bcf5-05f754057bcd
        userCondition: null
    thumbFieldKey: null
handle: wizardError
hasTitleField: false
icon: null
name: 'Wizard Error'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
