columnSuffix: null
contentColumnType: string
handle: authors
instructions: null
name: Authors
searchable: false
settings:
  entryTypes:
    -
      uid: cf8deda4-e468-4725-8360-4b1f350a3eb9
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
