columnSuffix: null
contentColumnType: string
handle: blockButtons
instructions: null
name: 'Block buttons'
searchable: false
settings:
  entryTypes:
    -
      handle: button
      uid: 95ca3702-ecb6-4427-9617-687cdf6f2a45
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
