columnSuffix: null
handle: buttonURL2
instructions: null
name: 'Block buttons - Button - Button URL'
searchable: false
settings:
  fullGraphqlData: false
  maxLength: 255
  showLabelField: false
  types:
    - entry
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
