columnSuffix: null
contentColumnType: text
handle: cb2_blockCopy
instructions: null
name: 'Block copy'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  css: null
  cssFile: null
  defaultTransform: ''
  enableSourceEditingForNonAdmins: false
  fullGraphqlData: false
  headingLevels:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  js: null
  jsFile: Default.json
  options: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  toolbar:
    - sourceEditing
    - '|'
    - heading
    - '|'
    - blockQuote
    - codeBlock
    - bold
    - italic
    - bulletedList
    - numberedList
    - insertTable
    - link
    - insertImage
    - mediaEmbed
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
