contentColumnType: text
fieldGroup: 3098be97-8925-4ee2-8878-d45da5d66168
handle: cb2_blockTitle
instructions: ''
name: 'Block title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
