columnSuffix: null
contentColumnType: string
handle: cb2_blockButtons
instructions: null
name: 'Block buttons'
searchable: false
settings:
  entryTypes:
    -
      handle: button
      uid: 557167c6-3627-4b2e-a961-0943b14380c8
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
