columnSuffix: null
contentColumnType: string
handle: historyTimelineDirection
instructions: 'Which side of the timeline do you want this to display?'
name: 'History timeline direction'
searchable: false
settings:
  columnType: string
  options:
    -
      __assoc__:
        -
          - label
          - Left
        -
          - value
          - left
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Right
        -
          - value
          - right
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
