columnSuffix: null
contentColumnType: string
handle: iconContentBlock
instructions: null
name: 'Icon content block'
searchable: false
settings:
  entryTypes:
    -
      uid: a768c059-82a6-4fd6-8f1f-07be0fa51789
  maxEntries: null
  minEntries: null
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
