columnSuffix: null
contentColumnType: string
handle: informationEmail
instructions: null
name: 'Information email'
searchable: false
settings:
  placeholder: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
