columnSuffix: null
handle: sideInformation
instructions: null
name: 'Side information'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 633fc42c-791f-4578-a6bf-d1784977571a # Information
  includeTableView: false
  maxEntries: 2
  minEntries: 2
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
