columnSuffix: null
contentColumnType: string
handle: sideInformation
instructions: null
name: 'Side information'
searchable: false
settings:
  entryTypes:
    -
      uid: 633fc42c-791f-4578-a6bf-d1784977571a
  maxEntries: 2
  minEntries: 2
  propagationKeyFormat: null
  propagationMethod: all
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
