contentColumnType: text
fieldGroup: 24ff0072-4ed1-4870-82c2-ff7ea9c68730
handle: youtubeVideoId
instructions: 'Example: 0FmAy9Rl__s'
name: 'YouTube video ID'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
