dateModified: 1774283354
email:
  fromEmail: investorportal@liwacap.com
  fromName: 'Liwa Capital website'
  replyToEmail: null
  template: ''
  transportSettings:
    encryptionMethod: tls
    host: smtp.office365.com
    password: LiwaAGG@2023
    port: '587'
    timeout: '10'
    useAuthentication: '1'
    username: investorportal@liwacap.com
  transportType: craft\mail\transportadapters\Smtp
meta:
  __names__:
    8f179eeb-233d-42c2-82af-ffff018d0f53: Images # Images
    c6db17d0-6f0e-4883-8685-a42d1ab5c7dd: 'Company information' # Company information
    d1808fcc-810d-4c80-9a58-0a1eb0b12285: 'Contact us block' # Contact us block
plugins:
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      prependSender: 'On behalf of'
      prependSubject: 'New message from Liwa Capital website'
      successFlashMessage: 'Your message has been sent.'
      toEmail: info@liwacap.com
  contact-form-honeypot:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  field-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  mailgun:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  simple-sharing:
    edition: standard
    enabled: false
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Liwa Capital'
  retryDuration: null
  schemaVersion: 3.8.0.1
  timeZone: Asia/Dubai
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
