defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 5206b1ed-3576-4a61-b5c4-35824797bec4 # Approach
handle: approach
maxAuthors: 1
name: Approach
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  a0170692-9bc8-4fc5-8c51-66a642669e82: # Liwa Capital
    enabledByDefault: true
    hasUrls: true
    template: approach
    uriFormat: our-approach
type: single
