defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: d5c97bf7-e24c-4b81-84c9-98551e1135dd # Contact
handle: contact
maxAuthors: 1
name: Contact
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  a0170692-9bc8-4fc5-8c51-66a642669e82: # Liwa Capital
    enabledByDefault: true
    hasUrls: true
    template: contact
    uriFormat: contact
type: single
