defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 0b2fbfcf-97ca-4c58-8535-841e9046bf90 # Disclaimer
handle: disclaimer
maxAuthors: 1
name: Disclaimer
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  a0170692-9bc8-4fc5-8c51-66a642669e82: # Liwa Capital
    enabledByDefault: true
    hasUrls: true
    template: copy-page
    uriFormat: disclaimer
type: single
