defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 5284dd70-cfe7-4452-abf9-e0fc45b2db6e # Leadspace
  -
    uid: 9010f513-cd24-4c5a-9af9-d08782e0e10a # History
handle: history
maxAuthors: 1
name: History
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  a0170692-9bc8-4fc5-8c51-66a642669e82: # Liwa Capital
    enabledByDefault: true
    hasUrls: true
    template: our-history
    uriFormat: 'our-history/{slug}'
structure:
  maxLevels: null
  uid: ec57c65b-68f5-4447-a0fd-a85916f0473a
type: structure
