defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 0deb07ea-7e00-49d5-baa5-760b9ddbc677 # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  a0170692-9bc8-4fc5-8c51-66a642669e82: # Liwa Capital
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: home-old
type: single
