defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: f3f40419-2a08-48e7-a459-69b431d9c132 # Insights-new
handle: insights
maxAuthors: 1
name: Insights-new
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  a0170692-9bc8-4fc5-8c51-66a642669e82: # Liwa Capital
    enabledByDefault: true
    hasUrls: true
    template: insights/entry
    uriFormat: 'insights/{slug}'
structure:
  maxLevels: 1
  uid: 9aae5e62-e09a-4e09-b581-33e23cc71ee6
type: structure
