defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: e47a1d47-4279-43e8-875f-d911fb150ab7 # News
handle: insightsOld
maxAuthors: 1
name: Insights
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  a0170692-9bc8-4fc5-8c51-66a642669e82: # Liwa Capital
    enabledByDefault: true
    hasUrls: true
    template: insights/entry
    uriFormat: 'insights-old/{slug}'
type: channel
