enableVersioning: true
handle: leadership
name: Leadership
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a0170692-9bc8-4fc5-8c51-66a642669e82:
    enabledByDefault: true
    hasUrls: true
    template: _includes/components/leadership
    uriFormat: 'leadership/{slug}'
structure:
  maxLevels: null
  uid: 08522d99-25ad-4d38-a9a7-4e12a2cb6aab
type: structure
