enableVersioning: true
handle: marketUpdatesSignUp
name: 'Market Updates Sign Up'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a0170692-9bc8-4fc5-8c51-66a642669e82:
    enabledByDefault: true
    hasUrls: true
    template: market_updates/index
    uriFormat: market-updates-sign-up
type: single
