defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 12cea5a5-f206-41ae-9579-a9bf56c7aa37 # New Contact
handle: newContact
maxAuthors: 1
name: 'New Contact'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  a0170692-9bc8-4fc5-8c51-66a642669e82: # Liwa Capital
    enabledByDefault: true
    hasUrls: true
    template: new-contact
    uriFormat: new-contact
type: single
