enableVersioning: true
handle: offer
name: 'What We Offer'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  a0170692-9bc8-4fc5-8c51-66a642669e82:
    enabledByDefault: true
    hasUrls: true
    template: offer/index
    uriFormat: what-we-offer
type: single
