tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        disabled: false
        elementCondition: null
        id: null
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: 5a81c345-d7c6-47c6-b138-6d705849be98
        userCondition: null
        warning: null
        width: 100
      -
        attribute: countryCode
        elementCondition: null
        id: null
        instructions: null
        label: null
        orientation: null
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: 16dc465d-342a-41f1-88ce-918ac4f10005
        userCondition: null
        warning: null
        width: 100
      -
        elementCondition: null
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: d1eef1f3-5597-4904-b713-d630818d4a87
        userCondition: null
        warning: null
    name: Content
    uid: 6f385ec4-1e0e-4240-8365-bb11031085b3
    userCondition: null
